### ISSUE TITLE
/usr/include/CL/cl2.hpp:1525: undefined reference to `clReleaseContext'

### ISSUE THREAD

**Issue by eddydw** [Xilinx/Vitis-In-Depth-Tutorial#10]
Hi

When running make build TARGET=sw_emu I get following errors (see below)

(base) xbeengsae01:/group/xirguup/eddydw/Vitis-In-Depth-Tutorial/Hardware_Accelerators/Introduction/03-Algorithm_Acceleration/docs/module1_baseline $ make build TARGET=sw_emu
mkdir -p ./build
g++ -D__USE_XOPEN2K8 -I/proj/xbuilds/XRT/2020.1/202010.2.6.655/packages/x86_64/xrt-2.6.655_ubuntu_18.04/opt/xilinx/xrt/include/ -I/proj/xbuilds/SWIP/2020.1_0602_1208/installs/lin64/Vivado/2020.1/include/ -I./src -O2 -g -Wall -fmessage-length=0 -std=c++0x -L/proj/xbuilds/XRT/2020.1/202010.2.6.655/packages/x86_64/xrt-2.6.655_ubuntu_18.04/opt/xilinx/xrt/lib/ -lOpenCL -lpthread -lrt -lstdc++ -o build/test.exe ./src/test.cpp ./src/xcl2.cpp
/tmp/cchyBY8A.o: In function `cl::Context::~Context()':
/usr/include/CL/cl2.hpp:1525: undefined reference to `clReleaseContext'
/tmp/cchyBY8A.o: In function `cl::CommandQueue::~CommandQueue()':
/usr/include/CL/cl2.hpp:1534: undefined reference to `clReleaseCommandQueue'
/tmp/cchyBY8A.o: In function `cl::Device::~Device()':
/usr/include/CL/cl2.hpp:1490: undefined reference to `clReleaseDevice'
/tmp/cchyBY8A.o: In function `cl::CommandQueue::enqueueMigrateMemObjects(std::vector<cl::Memory, std::allocator<cl::Memory> > const&, unsigned long, std::vector<cl::Event, std::allocator<cl::Event> > const*, cl::Event*) const':
/usr/include/CL/cl2.hpp:7950: undefined reference to `clEnqueueMigrateMemObjects'
/usr/include/CL/cl2.hpp:1579: undefined reference to `clReleaseEvent'
/tmp/cchyBY8A.o: In function `std::vector<cl::Device, std::allocator<cl::Device> >::~vector()':
/usr/include/CL/cl2.hpp:1490: undefined reference to `clReleaseDevice'
/tmp/cchyBY8A.o: In function `cl::detail::param_traits<cl::detail::cl_device_info, 4139>::param_type cl::Device::getInfo<4139>(int*) const':
/usr/include/CL/cl2.hpp:1429: undefined reference to `clGetDeviceInfo'
/usr/include/CL/cl2.hpp:1429: undefined reference to `clGetDeviceInfo'
/tmp/cchyBY8A.o: In function `std::vector<cl::Buffer, std::allocator<cl::Buffer> >::~vector()':
/usr/include/CL/cl2.hpp:1543: undefined reference to `clReleaseMemObject'
/tmp/cchyBY8A.o: In function `std::vector<std::vector<cl::Event, std::allocator<cl::Event> >, std::allocator<std::vector<cl::Event, std::allocator<cl::Event> > > >::~vector()':
/usr/include/CL/cl2.hpp:1579: undefined reference to `clReleaseEvent'
/tmp/cchyBY8A.o: In function `std::vector<cl::Memory, std::allocator<cl::Memory> >::~vector()':
/usr/include/CL/cl2.hpp:1543: undefined reference to `clReleaseMemObject'
/tmp/cchyBY8A.o: In function `std::vector<cl::Device, std::allocator<cl::Device> >::_M_default_append(unsigned long)':
/usr/include/CL/cl2.hpp:1490: undefined reference to `clReleaseDevice'
/tmp/cchyBY8A.o: In function `std::vector<cl::Event, std::allocator<cl::Event> >::_M_default_append(unsigned long)':
/usr/include/CL/cl2.hpp:1579: undefined reference to `clReleaseEvent'
/tmp/cchyBY8A.o: In function `std::vector<cl::Event, std::allocator<cl::Event> >::resize(unsigned long)':
/usr/include/CL/cl2.hpp:1579: undefined reference to `clReleaseEvent'
/tmp/cchyBY8A.o: In function `void std::vector<cl::Memory, std::allocator<cl::Memory> >::_M_realloc_insert<cl::Memory const&>(__gnu_cxx::__normal_iterator<cl::Memory*, std::vector<cl::Memory, std::allocator<cl::Memory> > >, cl::Memory const&)':
/usr/include/CL/cl2.hpp:1541: undefined reference to `clRetainMemObject'
/usr/include/CL/cl2.hpp:1543: undefined reference to `clReleaseMemObject'
/usr/include/CL/cl2.hpp:1543: undefined reference to `clReleaseMemObject'
/tmp/cchyBY8A.o: In function `main':
/usr/include/CL/cl2.hpp:1479: undefined reference to `clRetainDevice'
/usr/include/CL/cl2.hpp:2689: undefined reference to `clCreateContext'
/usr/include/CL/cl2.hpp:6979: undefined reference to `clCreateCommandQueue'
/usr/include/CL/cl2.hpp:6595: undefined reference to `clCreateKernel'
/usr/include/CL/cl2.hpp:3670: undefined reference to `clCreateBuffer'
/usr/include/CL/cl2.hpp:1543: undefined reference to `clReleaseMemObject'
/usr/include/CL/cl2.hpp:8224: undefined reference to `clFinish'
/usr/include/CL/cl2.hpp:5858: undefined reference to `clSetKernelArg'
/usr/include/CL/cl2.hpp:5858: undefined reference to `clSetKernelArg'
/usr/include/CL/cl2.hpp:8224: undefined reference to `clFinish'
/usr/include/CL/cl2.hpp:8001: undefined reference to `clEnqueueTask'
/usr/include/CL/cl2.hpp:8224: undefined reference to `clFinish'
/usr/include/CL/cl2.hpp:8224: undefined reference to `clFinish'
/usr/include/CL/cl2.hpp:1570: undefined reference to `clReleaseKernel'
/usr/include/CL/cl2.hpp:1561: undefined reference to `clReleaseProgram'
/usr/include/CL/cl2.hpp:1534: undefined reference to `clReleaseCommandQueue'
/usr/include/CL/cl2.hpp:1525: undefined reference to `clReleaseContext'
/usr/include/CL/cl2.hpp:1490: undefined reference to `clReleaseDevice'
/usr/include/CL/cl2.hpp:1490: undefined reference to `clReleaseDevice'
/usr/include/CL/cl2.hpp:6197: undefined reference to `clCreateProgramWithBinary'
/usr/include/CL/cl2.hpp:1534: undefined reference to `clReleaseCommandQueue'
/usr/include/CL/cl2.hpp:1525: undefined reference to `clReleaseContext'
/usr/include/CL/cl2.hpp:1490: undefined reference to `clReleaseDevice'
/usr/include/CL/cl2.hpp:1570: undefined reference to `clReleaseKernel'
/usr/include/CL/cl2.hpp:1561: undefined reference to `clReleaseProgram'
/usr/include/CL/cl2.hpp:1543: undefined reference to `clReleaseMemObject'
/usr/include/CL/cl2.hpp:1534: undefined reference to `clReleaseCommandQueue'
/tmp/ccBLfNMR.o: In function `xcl::get_devices(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/include/CL/cl2.hpp:2475: undefined reference to `clGetPlatformIDs'
/usr/include/CL/cl2.hpp:1429: undefined reference to `clGetPlatformInfo'
/usr/include/CL/cl2.hpp:2346: undefined reference to `clGetDeviceIDs'
/usr/include/CL/cl2.hpp:1429: undefined reference to `clGetPlatformInfo'
/usr/include/CL/cl2.hpp:2481: undefined reference to `clGetPlatformIDs'
/usr/include/CL/cl2.hpp:2352: undefined reference to `clGetDeviceIDs'
/usr/include/CL/cl2.hpp:1479: undefined reference to `clRetainDevice'
/usr/include/CL/cl2.hpp:1490: undefined reference to `clReleaseDevice'
/usr/include/CL/cl2.hpp:1490: undefined reference to `clReleaseDevice'
/usr/include/CL/cl2.hpp:1490: undefined reference to `clReleaseDevice'
/usr/include/CL/cl2.hpp:1490: undefined reference to `clReleaseDevice'
collect2: error: ld returned 1 exit status
Makefile:101: recipe for target 'build/test.exe' failed
make: *** [build/test.exe] Error 1

**Comment by rwarmstr** [comment]
This should be related to the LIBRARY_PATH issue in #9, we added a note to the tutorial.
