### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by eddydw** [Xilinx/Vitis-In-Depth-Tutorial#11]
When running g++ cpu_cholesky.cpp test.cpp matrixUtility.hpp -std=c++0x -O3 -o test
./test -M 16 -N 16 -seed 12

I get a Segmentation Fault

**Comment by f-rivo** [comment]
See **note 1** in the page: https://github.com/Xilinx/Vitis-In-Depth-Tutorial/blob/master/Hardware_Accelerators/Introduction/03-Algorithm_Acceleration/docs/cpu_src/README.md.
Depending on the stack size on your server, the execution of that program might fail.
On Nimbix, the server we tested have unlimited stack sizes and do not exhibit the problem.

**Comment by rwarmstr** [comment]
@eddydw Is this issue still pending? If not please let me know so we can close.

**Comment by rwarmstr** [comment]
Having not heard back will close for now.
