### ISSUE TITLE
ERROR: S_AXI_CONTROL remap entry is absent in xmlbin

### ISSUE THREAD

**Issue by estebanpw** [Xilinx/Vitis-In-Depth-Tutorial#12]
Hello,

I am new to Vitis and Vivado. I am trying to follow the Vitis-In-Depth-Tutorial but I get the following error when I try to compile the vadd project for software emulation:

`ERROR: S_AXI_CONTROL remap entry is absent in xmlbin`

This one is followed afterwards by other errors, particularly `[XRT] ERROR: Failed to load xclbin.`, `[XRT] ERROR: No program executable for device`  and `[XRT] ERROR: buffer (2) is not resident in device (0)` but I assume that these might be linked to the first one. 

Also these warnings are shown:

`[XRT] WARNING: Host buffer (0) has no bank assignment and is not used as kernel argument before first enqueue operation; allocating in default memory bank '0'.
[XRT] WARNING: Host buffer (1) has no bank assignment and is not used as kernel argument before first enqueue operation; allocating in default memory bank '0'.
[XRT] WARNING: Host buffer (2) has no bank assignment and is not used as kernel argument before first enqueue operation; allocating in default memory bank '0'.` 

The steps that I followed:
1. Setting up environment. I do this by issuing:

`source /tools/Xilinx/Vitis/2019.2/settings64.sh`
`source /opt/xilinx/xrt/setup.sh`

And the U200 export, which is:

`export PLATFORM_REPO_PATHS=/opt/xilinx/platforms/xilinx_u200_xdma_201830_2` 

2. Then I go to the folder `sw_emu` and compile:

`g++ -Wall -g -std=c++11 ../../src/host.cpp -o app.exe -I${XILINX_XRT}/include/ -L${XILINX_XRT}/lib/ -lOpenCL -lpthread -lrt -lstdc++emconfigutil --platform xilinx_u200_xdma_201830_2 --nd 1`
`v++ -c -t sw_emu --config ../../src/u200.cfg -k vadd -I../../src ../../src/vadd.cpp -o vadd.xo `
`v++ -l -t sw_emu --config ../../src/u200.cfg ./vadd.xo -o vadd.xclbin`

All of these run without any problems nor warnings. 

3. Then I proceed to the export and run:

`export XCL_EMULATION_MODE=sw_emu`
`./app.exe`

This is the output generated:

> [XXXXXXX@YYYYY sw_emu]$ ./app.exe
> INFO: Found Xilinx Platform
> INFO: Loading 'vadd.xclbin'
> ERROR: S_AXI_CONTROL remap entry is absent in xmlbin
> XRT build version: 2.5.309
> Build hash: 9a03790c11f066a5597b133db737cf4683ad84c8
> Build date: 2020-02-24 02:54:37
> Git branch: 2019.2_PU2
> PID: 42663
> UID: 826
> [Tue Oct 20 14:24:35 2020]
> HOST: fpga2
> EXE: XXXXXXXXXXXX/Vitis-In-Depth-Tutorial/Getting_Started/Vitis/example/u200/sw_emu/app.exe
> [XRT] ERROR: Failed to load xclbin.
> [XRT] WARNING: Host buffer (0) has no bank assignment and is not used as kernel argument before first enqueue operation; allocating in default memory bank '0'.
> [XRT] WARNING: Host buffer (1) has no bank assignment and is not used as kernel argument before first enqueue operation; allocating in default memory bank '0'.
> [XRT] WARNING: Host buffer (2) has no bank assignment and is not used as kernel argument before first enqueue operation; allocating in default memory bank '0'.
> [XRT] ERROR: No program executable for device
> [XRT] ERROR: buffer (2) is not resident in device (0)
> Error: Result mismatch
> i = 0 CPU result = 2349 Device result = 0
> TEST FAILED
> terminate called after throwing an instance of 'xrt::error'
>   what():  event 4 never submitted
> terminate called recursively
> terminate called recursively
> *** Error in `./app.exe': double free or corruption (!prev): 0x0000000001850710 ***

What can I do to fix this? 

=============Log of the first v++ compilation ==============================:

> ****** Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC v2019.2 (64-bit)
>   **** SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
>   **** IP Build 2700528 on Thu Nov  7 00:09:20 MST 2019
>     ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
> 
> source /tools/Xilinx/Vivado/2019.2/scripts/vivado_hls/hls.tcl -notrace
> INFO: [HLS 200-10] Running '/tools/Xilinx/Vivado/2019.2/bin/unwrapped/lnx64.o/vivado_hls'
> INFO: [HLS 200-10] For user 'XXXXX' on host 'YYYYYYYYYY' (Linux_x86_64 version 3.10.0-1127.8.2.el7.x86_64) on Tue Oct 20 13:00:37 CEST 2020
> INFO: [HLS 200-10] On os "CentOS Linux release 7.8.2003 (Core)"
> INFO: [HLS 200-10] In directory 'XXXXXXXXX/Vitis-In-Depth-Tutorial/Getting_Started/Vitis/example/u200/sw_emu/_x/vadd/vadd'
> Sourcing Tcl script 'vadd.tcl'
> INFO: [HLS 200-10] Creating and opening project 'XXXXXXXXXXX/Vitis-In-Depth-Tutorial/Getting_Started/Vitis/example/u200/sw_emu/_x/vadd/vadd/vadd'.
> INFO: [HLS 200-10] Adding design file 'XXXXXXXXXXXX/Vitis-In-Depth-Tutorial/Getting_Started/Vitis/example/src/vadd.cpp' to the project
> INFO: [HLS 200-10] Creating and opening solution 'XXXXXXXXXXXX/Vitis-In-Depth-Tutorial/Getting_Started/Vitis/example/u200/sw_emu/_x/vadd/vadd/vadd/solution'.
> INFO: [HLS 200-10] Setting target device to 'xcu200-fsgd2104-2-e'
> INFO: [SYN 201-201] Setting up clock 'default' with a period of 3.333ns.
> INFO: [HLS 200-435] Setting 'config_sdx -target' configuration: config_export -vivado_optimization_level=0
> INFO: [HLS 200-435] Setting 'config_export -vivado_optimization_level' configuration: config_export -vivado_phys_opt=none
> INFO: [HLS 200-435] Setting 'config_sdx -target' configuration: config_compile -pipeline_loops=64
> INFO: [XFORM 203-1171] Pipeline the innermost loop with trip count more than 64 or its parent loop when its trip count is less than or equal 64.
> INFO: [HLS 200-435] Setting 'config_sdx -target' configuration: config_compile -name_max_length=80
> INFO: [XFORM 203-1161] The maximum of name length is set into 80.
> INFO: [HLS 200-435] Setting 'config_sdx -target' configuration: config_schedule -enable_dsp_full_reg=1
> INFO: [HLS 200-435] Setting 'config_sdx -target' configuration: config_rtl -register_reset_num=3
> INFO: [HLS 200-435] Setting 'config_sdx -target' configuration: config_rtl -module_auto_prefix=1
> INFO: [HLS 200-435] Setting 'config_sdx -target' configuration: config_interface -m_axi_addr64=1
> INFO: [HLS 200-435] Setting 'config_sdx -target' configuration: set_clock_uncertainty 27%
> INFO: [SYN 201-201] Setting up clock 'default' with an uncertainty of 0.9ns.
> INFO: [SYN 201-201] Setting up clock 'default' with an uncertainty of 0.9ns.
> INFO: [SCHED 204-61] Option 'relax_ii_for_timing' is enabled, will increase II to preserve clock frequency constraints.
> INFO: [HLS 200-10] Analyzing design file 'XXXXXXXXXXXXX/Vitis-In-Depth-Tutorial/Getting_Started/Vitis/example/src/vadd.cpp' ... 
> INFO: [HLS 200-111] Finished Linking Time (s): cpu = 00:00:08 ; elapsed = 00:00:08 . Memory (MB): peak = 1052.188 ; gain = 532.148 ; free physical = 93862 ; free virtual = 124163
> INFO: [HLS 200-111] Finished Checking Pragmas Time (s): cpu = 00:00:08 ; elapsed = 00:00:08 . Memory (MB): peak = 1052.188 ; gain = 532.148 ; free physical = 93862 ; free virtual = 124163
> HLS completed successfully
> INFO: [Common 17-206] Exiting vivado_hls at Tue Oct 20 13:00:46 2020...

The second log of v++ is much larger, but I can attach it if necessary. Thanks a lot for your time.

**Comment by ThomasXilinx** [comment]
This tutorial relies on capabilities which were added in Vitis 20.1. Therefore, it will not work out-of-the-box in Vitis 19.2. Specifically, Vitis 20.1 requires fewer pragmas in the kernel code. To get this example to work, you should either upgrade to Vitis 20.1, or replace the contents of the vadd.cpp file the code included below. Upgrading to 20.1 is recommended as it will let you run successfully more of the tutorials included on this repository.

```cpp
extern "C" {
	void vadd(
	        const unsigned int *in1, // Read-Only Vector 1
	        const unsigned int *in2, // Read-Only Vector 2
	        unsigned int *out,       // Output Result
	        int size                 // Size in integer
	        )
	{
#pragma HLS INTERFACE m_axi     port=in1    bundle=aximm1   offset=slave
#pragma HLS INTERFACE m_axi     port=in2    bundle=aximm2   offset=slave
#pragma HLS INTERFACE m_axi     port=out    bundle=aximm1   offset=slave
#pragma HLS INTERFACE s_axilite port=in1    bundle=control
#pragma HLS INTERFACE s_axilite port=in2    bundle=control
#pragma HLS INTERFACE s_axilite port=out    bundle=control
#pragma HLS INTERFACE s_axilite port=size   bundle=control
#pragma HLS INTERFACE s_axilite port=return bundle=control

	    for(int i = 0; i < size; ++i)
	    {
	        out[i] = in1[i] + in2[i];
	    }
	}
}
```

**Comment by estebanpw** [comment]
Thanks a lot @ThomasXilinx now it worked
I will check back at my lab whether it can be upgraded. 
In case it cant be done, are differences between versions mostly in the pragmas? Do you think I can work around them?

Bests,
Esteban

**Comment by ThomasXilinx** [comment]
You only need these pragma changes to complete the rest of the Vitis 101 Lab with Vitis 19.2.  Other tutorials on this repo do require Vitis 20.1. So the sooner you can upgrade, the better.
