### ISSUE TITLE
Error adapting tutorials to DPUV1

### ISSUE THREAD

**Issue by rubende** [Xilinx/Vitis-In-Depth-Tutorial#15]
Hello,

I am trying to adapt the tutorial [04-Keras_GoogleNet_ResNet](https://github.com/Xilinx/Vitis-In-Depth-Tutorial/tree/master/Machine_Learning/Design_Tutorials/04-Keras_GoogleNet_ResNet) to use these models on a U200 board (DPUV1).

For this I modify, without giving me problems in the process, the compilation process, changing the architecture target
 and adding the flag --quant_info.

The problem comes up when I am going to make an inference. Based on another tutorial, I've created a python file (which I'm attaching) to load and make inference with the model. 3 of the 4 models give me the following error:
WARNING 
Schedule   Failed 
list index out of range
EXCEPTION IN (/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/vaic/dpuv1/bin/xfdnn_compiler_base.py, LINE 1488 "schdl,max_items = ComputeMemory(graph, schdl, I,args)"): list index out of range

The fourth, miniResNet, generate the following error:
File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/vaic/dpuv1/quantz/deephi_quant_info.py", line 67, in set
assert inputs is not None or outputs is not None, self._name
AssertionError: batch_normalization_1/FusedBatchNormV3_1

Can you give me some indication about the process of adapting this tutorial to DPUV1? Am I forgetting any additional changes? Are these networks not compatible with DPUV1 for some reason?

Thank you.
[inference_u250.zip](https://github.com/Xilinx/Vitis-In-Depth-Tutorial/files/5588514/inference_u250.zip)

**Comment by allyzhou** [comment]
This tutorial wasn't tried on DPUv1, which is relatively old version of DPU, so there maybe some in-compatible issue, we'll look into the issue and get back to you,  but it might take some time. Thanks.
