### ISSUE TITLE
Clock setting in custom platform creation tutorial

### ISSUE THREAD

**Issue by doonny** [Xilinx/Vitis-In-Depth-Tutorial#18]
in the custom platform creation tutorial, clock creation part (https://github.com/Xilinx/Vitis-In-Depth-Tutorial/blob/master/Vitis_Platform_Creation/Introduction/02-Edge-AI-ZCU104/step1.md)
It was told to **"set the id's of clk_{100,200,400}m to {2,1,0}"**, but in the following figure, the id of clk_200m is 0, which is also the default clock.
![捕获](https://user-images.githubusercontent.com/8196382/103336274-963ac480-4ab2-11eb-8219-ddca129ff114.PNG)

Which description is the correct one ?

**Comment by imrickysu** [comment]
The screenshot is matching the ref_files. It should be "clk_{100,200,400}m to {2,0,1}". The document will be updated soon.
Actually the clock ID order doesn't matter too much for platform developers. It just needs to start from 0.
Application developers can assign specific clocks to kernels during [v++ link](https://www.xilinx.com/html_docs/xilinx2020_2/vitis_doc/vitiscommandcompiler.html#ans1568640653312) by clock ID or by clock frequency.
