### ISSUE TITLE
Custom Platform about Interrupt setting

### ISSUE THREAD

**Issue by doonny** [Xilinx/Vitis-In-Depth-Tutorial#19]
In the custom platform creation tutorial  on zcu104 board,  step 1  Adding Interrupt Support (https://github.com/Xilinx/Vitis-In-Depth-Tutorial/blob/master/Vitis_Platform_Creation/Introduction/02-Edge-AI-ZCU104/step1.md), the tutorial added an AXI interrupt Controller, and set the number of  input intr to 1 (auto), but in the following PFM_IRQ setting, it used 32 inputs:
```
set_property PFM.IRQ {intr {id 0 range 32}} [get_bd_cells /axi_intc_0]
```
However, in the Official Embedded Platform (https://github.com/Xilinx/Vitis_Embedded_Platform_Source/tree/master/Xilinx_Official_Platforms/xilinx_zc706_base),  it also created a concat module and explicitly created 32 input interrupt signals like follow:

![捕获](https://user-images.githubusercontent.com/8196382/103994301-c3cdef00-51d1-11eb-9574-2f7a7abb7789.PNG)

My question is : Can this concat module be removed from here as did in the custom platform creation tutorial ?  Will v++ automatically connect what is needed without explicitly create 32 input interrupt signals ?

**Comment by imrickysu** [comment]
Short answer: Yes, concat can be removed in Vitis 2020.2.

The two use cases are both valid. V++ now can connect to interrupt signals defined by PFM.IRQ. Concat IP was required in 2019.2. V++ enhanced to be able to instantiate contact IP afterwards.

**Comment by imrickysu** [comment]
The simplified example can also be seen in https://github.com/Xilinx/Vitis_Embedded_Platform_Source/blob/master/Xilinx_Official_Platforms/xilinx_zcu102_base/hw/xsa_scripts/pfm_decls.tcl

**Comment by doonny** [comment]
Thx for the reply
