### ISSUE TITLE
Getting_Started/Vitis_HLS instructions point to wrong repo

### ISSUE THREAD

**Issue by shaunclimbon** [Xilinx/Vitis-In-Depth-Tutorial#24]
Under this section: [https://github.com/f-rivo/Vitis-In-Depth-Tutorial/tree/master/Getting_Started/Vitis_HLS#accessing-the-tutorial-reference-files](https://github.com/f-rivo/Vitis-In-Depth-Tutorial/tree/master/Getting_Started/Vitis_HLS#accessing-the-tutorial-reference-files)

A link to the "Vitis-Tutorials" repo is provided but it should be "Vitis-In-Depth-Tutorial"

**Comment by rwarmstr** [comment]
Hi @mkycrb, apologies for the delay in responding, these repos are mirrors for legacy / bookmarking purposes. The https://github.com/Xilinx/Vitis-Tutorials repo is the primary one, so the links redirect there. The content is identical.
