### ISSUE TITLE
Cannot find model

### ISSUE THREAD

**Issue by udara28** [Xilinx/Vitis-In-Depth-Tutorial#5]
I'm trying to run the following part of the tutorial:
Vitis-In-Depth-Tutorial/Machine_Learning/Introduction/03-Basic/Module_2/

When I run below command:
```
./test_performance_refinedet test_performance_refinedet.list
```

I get the following error:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0909 00:31:29.154747  1138 configurable_dpu_task_imp.cpp:103] cannot find model <test_performance_refinedet.list> after checking following dir:
	.
	/usr/share/vitis_ai_library/models
	/usr/share/vitis_ai_library/.models
*** Check failure stack trace: ***
Aborted
```

I found that there is a folder called /usr/share/vitis_ai_library/models in my SD card installation. So I'm trying to understand what's this error is about. Please help me resolve this issue.

Best Regards,
Udara

**Comment by fanz-amd** [comment]
Hi Udara,

Thanks for your feedback.
The model name is missing in your command which leads to the error.
The syntax is like:  ./test_performance_refinedet **refinedet_pruned_0_96** test_performance_refinedet.list

**Comment by udara28** [comment]
@fanz-xlnx Thank you for pointing out this mistake. The command is running as described with the correct command.
