### ISSUE TITLE
segmentation fault cholesky_cpu.cpp

### ISSUE THREAD

**Issue by basileus93** [Xilinx/Vitis-In-Depth-Tutorial#8]
Hi,

In /Hardware_Accelerators/Introduction/03-Algorithm_Acceleration/ when I am running the CPU version I am getting segmentation fault with different dimensions (512-2048) and other CPUs.
I solved the problem modifying line 23 in cholesky_cpu.cpp:
`static double dataA[MAXN][MAXN];`
Could you tell me if this is the right way to proceed?

Thanks

**Comment by f-rivo** [comment]
In the current example, the matrix is passed through the stack and could exceed your server stack size limit (see Note 1 in the tutorial page).  If you cannot change the stack size, then using static is probably a good workaround.

**Comment by basileus93** [comment]
Thanks, I was able to change the stack up to 16384, but it does not work. I will use the `static` workaround.
