### ISSUE TITLE
hw emulation flow fails of the getting started project

### ISSUE THREAD

**Issue by eddydw** [Xilinx/Vitis-In-Depth-Tutorial#9]
when running Vitis-In-Depth-Tutorial/Getting_Started/Vitis/example/u200/hw_emu : make all in h

[13:50:24] Run vpl: Step config_hw_emulation: Failed
[13:50:30] Run vpl: FINISHED. Run Status: config_hw_emulation ERROR
ERROR: [VPL 60-773] In '/group/xirguup/eddydw/Vitis-In-Depth-Tutorial/Getting_Started/Vitis/example/u200/hw_emu/_x/link/vivado/vpl/runme.log', caught Tcl error:  ./elaborate.sh: line 20: LIBRARY_PATH: unbound variable
ERROR: [VPL 60-2373] In '/group/xirguup/eddydw/Vitis-In-Depth-Tutorial/Getting_Started/Vitis/example/u200/hw_emu/_x/link/vivado/vpl/runme.log', caught error: ERROR: caught error: ./elaborate.sh: line 20: LIBRARY_PATH: unbound variable
ERROR: [VPL 60-2373] In '/group/xirguup/eddydw/Vitis-In-Depth-Tutorial/Getting_Started/Vitis/example/u200/hw_emu/_x/link/vivado/vpl/vivado.log', caught error: ERROR: caught error: ./elaborate.sh: line 20: LIBRARY_PATH: unbound variable
ERROR: [VPL 60-1328] Vpl run 'vpl' failed
ERROR: [VPL 60-806] Failed to finish platform linker
INFO: [v++ 60-1442] [13:50:33] Run run_link: Step vpl: Failed
Time (s): cpu = 00:06:52 ; elapsed = 00:03:59 . Memory (MB): peak = 1307.008 ; gain = 0.000 ; free physical = 30591 ; free virtual = 106687
ERROR: [v++ 60-661] v++ link run 'run_link' failed
ERROR: [v++ 60-626] Kernel link failed to complete
ERROR: [v++ 60-703] Failed to finish linking
INFO: [v++ 60-1653] Closing dispatch client.
Makefile:13: recipe for target 'vadd.xclbin' failed
make: *** [vadd.xclbin] Error 1

**Comment by rwarmstr** [comment]
Related to the LIBRARY_PATH issue documented on Xilinx.com, we added a note to the tutorial and will close this.

[Xilinx AR 73698](https://www.xilinx.com/support/answers/73698.html)
